### PR TITLE
Upstream updates

### PR DESCRIPTION
**Pull request by chris18890**
hey @mtfurlan,

Great to see you're still doing dev work on Seltzer, I'd love to review & possibly pull your changes uptream; there's also been a lot of work done to Seltzer in the origin repo & they've diverged substantially now! Would you be interested in collaborating to merge in some of the differences?

All the best,

Chris 8-)

### CODE REVIEW

**Comment by mtfurlan** [comment]
Hey Chris, sorry on the delay getting back to you.
My goals for this are to get what i3 is currently using into a container so I can poke at it locally, and maybe containerize prod as well so we can separate the PHP environment from the other PHP stuff like mediawiki and wordpress.

I'm not really sure what our long-term plans involving seltzer are, right now we're looking into moving all our membership management into stripe because they will handle it and not have all the exciting issues we've been having.
We'll need  some interface on our side for that, but nobody here is really willing to work on PHP, so we're not really sure what to do.

Does upstream seltzer still track membership based on account balance?
One thing that horrified me and I want nothing to do with is that until a few years ago, the way we had "buy 11 months get one free" setup was that seltzer just lied about how much money people paid.
This made accounting and tax stuff much harder.

**Comment by chris18890** [comment]
No worries :)

Personally I find adding containerisation just overly complicates things, but YMMV, in my experience seltzer will work fine on whatever PHP & MySQL/MariaDB version MediaWiki/WordPress are using :)

Fair enough, at @FarsetLabs we use Nexudus, @SoMakeIt use a fork of @NottingHack's HMS2 (https://github.com/somakeit/hms2), & @HacManchester use a forked version of @ArthurGuy's BBMS (https://github.com/HACManchester/BBMembershipSystem)

Re tracking membership - I'd assume so, cause I don't recall making/seeing changes that it'd do things any differently! I've no idea how that would've been set up...

**Comment by mtfurlan** [comment]
Hey Chris, I'm finally getting back to this, but merging upstream is still pretty far away for us right now so I'm going to close this PR.

In the shorter term (hopefully) once I get the containerization stuff sorted I'll talk to you about if it would be helpful to port to you.
At least the development side should be helpful as long as it doesn't get in the way of prod.

**Comment by chris18890** [comment]
@mtfurlan Not a problem, shout if you need any help! :)

**Pull request closed without merging**
